name: Python testing using pytest

on: [push]

jobs:
  test:
    runs-on: python:3.11-slim-bullseye

    steps:
      - uses: actions/checkout@v4
      - name: Install package and test dependencies
        run: |
          python -m pip install .[test]
      - name: Test with pytest
        run: pytest --junitxml=junit/test-results.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always () }}




